#pragma once

#define QHA    LSFT_T(KC_A)
#define QHS    LGUI_T(KC_S)
#define QHD    LALT_T(KC_D)
#define QHF    LCTL_T(KC_F)
#define QHJ    RCTL_T(KC_J)
#define QHK    RALT_T(KC_K)
#define QHL    RGUI_T(KC_L)
#define QHQUOT RSFT_T(KC_QUOT)
#define QBZ    KC_Z
#define QBX    KC_X
#define QBC    KC_C
#define QBV    KC_V
#define QBM    KC_M
#define QBCOMM KC_COMM
#define QBDOT  KC_DOT
#define QBSLSH KC_SLSH
#define CHA    LSFT_T(KC_A)
#define CHR    LGUI_T(KC_R)
#define CHS    LALT_T(KC_S)
#define CHT    LCTL_T(KC_T)
#define CHN    RCTL_T(KC_N)
#define CHE    RALT_T(KC_E)
#define CHI    RGUI_T(KC_I)
#define CHQUOT RSFT_T(KC_QUOT)
#define CBZ    KC_Z
#define CBX    KC_X
#define CBC    KC_C
#define CBV    KC_V
#define CBM    KC_M
#define CBCOMM KC_COMM
#define CBDOT  KC_DOT
#define CBSLSH KC_SLSH
