#pragma once

#define QH_A    LSFT_T(KC_A)
#define QH_S    LGUI_T(KC_S)
#define QH_D    LALT_T(KC_D)
#define QH_F    LCTL_T(KC_F)
#define QH_J    RCTL_T(KC_J)
#define QH_K    RALT_T(KC_K)
#define QH_L    RGUI_T(KC_L)
#define QH_QUOT RSFT_T(KC_QUOT)
#define QB_Z    KC_Z
#define QB_X    KC_X
#define QB_C    KC_C
#define QB_V    KC_V
#define QB_M    KC_M
#define QB_COMM KC_COMM
#define QB_DOT  KC_DOT
#define QB_SLSH KC_SLSH
#define CH_A    LSFT_T(KC_A)
#define CH_R    LGUI_T(KC_R)
#define CH_S    LALT_T(KC_S)
#define CH_T    LCTL_T(KC_T)
#define CH_N    RCTL_T(KC_N)
#define CH_E    RALT_T(KC_E)
#define CH_I    RGUI_T(KC_I)
#define CH_QUOT RSFT_T(KC_QUOT)
#define CB_Z    KC_Z
#define CB_X    KC_X
#define CB_C    KC_C
#define CB_V    KC_V
#define CB_M    KC_M
#define CB_COMM KC_COMM
#define CB_DOT  KC_DOT
#define CB_SLSH KC_SLSH
