COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
RGBLIGHT_ENABLE = no 
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LTO_ENABLE = yes
SEND_STRING_ENABLE = yes
TRI_LAYER_ENABLE = yes
